# Generated by Django 2.1.4 on 2019-01-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='compile',
        ),
    ]
