# Generated by Django 2.1.4 on 2019-01-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0002_remove_todo_compile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
