# Generated by Django 2.1.4 on 2019-01-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
