# Generated by Django 2.1.4 on 2019-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0004_auto_20190128_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
